{
 "title": "dpx_showsite_ops - Temperature & Sensor Data Comparison",
 "description": "first dashboard to compare data flows from cloud (10m) vs ble (2s to 1m)",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Temperature - Govee Cloud VS Local BLE ",
   "type": "timeseries",
   "description": "this shows both govee cloud data and locally collected ble (bluetooth low energy) data. The ble data does not hit the cloud at all and is captured locally with custom esp32 hardware running open source software.",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 17 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r.source == \"gv_cloud\" or r.source == \"dpx_ops_decoder\")\n  |> filter(fn: (r) => r.sensor_type == \"temperature\")\n  |> filter(fn: (r) => r.device_name != \"h5074_4e6f\")\n  |> map(fn: (r) => ({r with _field: \n  r.source + \n  (if exists r.source_node then \" -- |\" + r.source_node + \"| - \" else \" - \") + \n  r.room + \" - \" + r.device_name\n}))\n  \n\n"
    }
   ]
  },
  {
   "title": "Temperature - Govee Cloud Data only",
   "type": "timeseries",
   "description": "10 Minute updates direct from govee cloud only",
   "gridPos": { "x": 0, "y": 17, "w": 24, "h": 7 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r.source == \"gv_cloud\")\n  |> filter(fn: (r) => r.sensor_type == \"temperature\")\n  |> filter(fn: (r) => r.device_name != \"h5074_4e6f\")\n  |> filter(fn: (r) => r.device_name != \"studio_5051_down\")\n  |> map(fn: (r) => ({r with _field: r.room +\" - \" + r.device_name}))\n"
    }
   ]
  },
  {
   "title": "Temperature - Bluetooth Low Energy Comparison (via dpx_ops_decoder)",
   "type": "timeseries",
   "description": "comparing Theeengs RX local on NUC PC vs OpenMQTT running on dpx_esp32 hardware",
   "gridPos": { "x": 0, "y": 24, "w": 24, "h": 12 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r.source == \"dpx_ops_decoder\")\n  |> filter(fn: (r) => r.sensor_type == \"temperature\")\n  |> filter(fn: (r) => r.device_name != \"h5074_4e6f\")\n  |> map(fn: (r) => ({r with _field: \"|\"+ r.source_node + \"| - \" + r.room +\" - \" + r.device_name}))\n\n  \n\n"
    }
   ]
  },
  {
   "title": "Sensor Battery Data",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 36, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r.device_name != \"h5074_4e6f\")\n  |> filter(fn: (r) => r.source_node == \"dpx_ops_1\")\n  |> filter(fn: (r) => r.sensor_type == \"battery\")\n  |> map(fn: (r) => ({r with _field: \"|\" + r.device_name + \"|\"}))\n  |> last()"
    }
   ]
  },
  {
   "title": "ESP 32 Sensor Signal Strength",
   "type": "gauge",
   "gridPos": { "x": 8, "y": 36, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r.device_name != \"h5074_4e6f\")\n  |> filter(fn: (r) => r.source_node == \"dpx_ops_1\")\n  |> filter(fn: (r) => r.sensor_type == \"rssi\")\n  |> map(fn: (r) => ({r with _field: \"|\" + r.device_name + \"|\"}))\n  |> last()"
    }
   ]
  },
  {
   "title": "Nuc Local BLE Signal Strength",
   "type": "gauge",
   "gridPos": { "x": 16, "y": 36, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r.device_name != \"h5074_4e6f\")\n  |> filter(fn: (r) => r.source_node == \"TheengsGateway\")\n  |> filter(fn: (r) => r.sensor_type == \"rssi\")\n  |> map(fn: (r) => ({r with _field: \"|\" + r.device_name + \"|\"}))\n  |> last()"
    }
   ]
  }
 ]
}